DEVICE: GPU
DATASET: EMNIST
N_CLIENT: 25
ADV:
  RANDOM:
    NUM: 5
  OPPOSITE:
    NUM: 5
  SWAP:
    NUM: 5
TRAIN_FRAC: 0.8

##Training 
TOTAL_TRIAL: 30
TOTAL_ROUND: 20

ESP_VALS: [0.1, 0.2, 0.3, 0.4, 0.5]
MIN_SAMPLES_VALS: [2, 3, 4, 5, 6]
METRIC_VALS: l1